### ISSUE TITLE
FTBFS on Debian Buster

### ISSUE THREAD

**Issue by sahabia** [paulguy/wudex#1]
First compiling main.c:
In file included from main.c:12:
util.h:42:5: error: conflicting types for ‘crypt’
 int crypt(const unsigned char const *in, unsigned char *out,
     ^~~~~
In file included from main.c:8:
/usr/include/unistd.h:1124:14: note: previous declaration of ‘crypt’ was here
 extern char *crypt (const char *__key, const char *__salt)

Second compiling util.c:
util.c: In function ‘decrypt_block’:
util.c:112:17: error: storage size of ‘c’ isn’t known
  EVP_CIPHER_CTX c;

...

openssl API seems to have changed in libssl:
aptitude show libssl-dev
Paquet : libssl-dev                                     
Version : 1.1.1b-1

Thanks for the tool.

**Comment by paulguy** [comment]
Try it now.  I no longer have any WUD files to test with so I don't know if it actually works but it does compile.

**Comment by sahabia** [comment]
It compiles successfully. Thanks a lot for the patch!

(FYI, It runs too but the extraction failed:

Key found for 3!
Key found for 4!
Invalid file table signature!
Failed to populate file tree for  ...
Failed to populate file trees!
Failed to read disc structure!

It seems I don't fire the command well.)

**Comment by paulguy** [comment]
It's been a long time since i've used it so I'm not super familiar with how it works.  It could easily be something wrong with my code.

**Comment by sahabia** [comment]
Ok. I'll try to dig a bit. Thanks.

**Comment by sahabia** [comment]
It finally works. The common key was not in a binary form.

echo -n "$common_key" | xxd -r -p > common_key.bin

**Comment by paulguy** [comment]
Good to hear this problem seems resolved.  If there're any other problems, feel free to open another issue. :)
